### ISSUE TITLE
How to use on local LAN? - Help

### ISSUE THREAD

**Issue by MichelDiz** [sh0umik/rancher-taiga#1]
I wanna test Taiga with Rancher, but in the machine doesn't open "taiga.test.de" Domain, and I can't acess through Local IP address in another machine.

There's no option to change ports or set "Localhost".

Cheers

**Comment by sh0umik** [comment]
It runs perfectly on local Lan . the taiga.test.de doesnt has any affect if you are running on local lan . Just replace the variable with real value . 
By local lan i am assuming you are taking about running via docker-compose

Here is what i rested few minutes ago 

```
postgres:
  image: postgres
  labels:
      io.rancher.scheduler.affinity:host_label_soft: taiga=true
  environment:
    POSTGRES_USER: taiga
    POSTGRES_PASSWORD: taiga
  volumes:
    - p_d_n2:/var/lib/postgresql/data
  restart: always

taigaback:
  image: htdvisser/taiga-back:stable
  labels:
      io.rancher.scheduler.affinity:host_label_soft: taiga=true
  environment:
    SECRET_KEY: examplesecretkey
    EMAIL_USE_TLS: 'True'
    EMAIL_HOST: smtp.gmail.com
    EMAIL_PORT: 587
    EMAIL_HOST_USER: youremail@gmail.com
    EMAIL_HOST_PASSWORD: yourpassword
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  links:
    - postgres:postgres
  volumes:
    - tgb_m:/usr/local/taiga/media
    - tgb_s:/usr/local/taiga/static
    - tgb_l:/usr/local/taiga/logs
  restart: always

taigafront:
  image: htdvisser/taiga-front-dist:stable
  labels:
      io.rancher.scheduler.affinity:host_label_soft: taiga=true
  links:
    - taigaback
  ports:
    - 0.0.0.0:80:80
  restart: always
```
